function xgd_table = NY_xgd_uc_v2(mpc)
%EI5k_XGD_UC xGenData table for 5k bus EI model unit commitment.

%   Assumptions and Notes:
%   1. All fossil generators can be turned on/off: CommitKey = 1.
%   2. CommitSched ........
%   3. Reserves and their associated prices (PositiveActiveReserveQuantity, 
%   NegativeActiveReserveQuantity, PositiveActiveReservePrice, 
%   NegativeActiveReservePrice) will not be considered.
%   4. Deviations from active power contract quantity will be assumed zero,
%   and their prices (PositiveActiveDeltaPrice, NegativeActiveDeltaPrice) 
%   will be set to zero.
%   5. Min up/down times (MinUp, MinDown) and ramping capability 
%   (PositiveLoadFollowReserveQuantity, NegativeLoadFollowReserveQuantity) 
%   are determined using historical data.
%
%   Last updated by Jeff on 07/17/2018

%% initial xGenData
define_constants;
ngens = length(mpc.gen(:,1));
Z = 1*10^-9*ones(ngens,1);
% R = 2*(mpc.gen(:,PMAX));
R = 2*(mpc.gen(:,PMAX) - min(0, mpc.gen(:,PMIN)));
xgd_table.colnames = {
    'CommitSched', ...
                    'InitialPg',...
                                    'RampWearCostCoeff',...  
                                        'PositiveActiveReservePrice',...
                                            'PositiveActiveReserveQuantity',...
                                                'NegativeActiveReservePrice',...
                                                    'NegativeActiveReserveQuantity',...
                                                        'PositiveActiveDeltaPrice',...
                                                            'NegativeActiveDeltaPrice',...
                                                                'PositiveLoadFollowReservePrice', ...
                                                                    'PositiveLoadFollowReserveQuantity', ...
                                                                        'NegativeLoadFollowReservePrice', ...
                                                                            'NegativeLoadFollowReserveQuantity', ...
    };
xgd_table.data = [
    ones(ngens,1)   mpc.gen(:,PG)   Z   Z   R   Z   R   Z   Z   Z   R   Z   R    
    ];
